# Nombre de la action
name: Build container and run VISE API testing

# Ejecución manual del workflow
on:
  workflow_dispatch:
    inputs:
      PORT:
        description: 'The port of your application'
        required: true
        default: "3000"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Descargar el código del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Configurar Docker Buildx
      - name: Setup docker
        uses: docker/setup-buildx-action@v3

      # Construir imagen Docker (Dockerfile en api-devops/app)
      - name: Build docker image
        run: |
          docker build -t devops-api:latest -f api-devops/app/Dockerfile api-devops/app

      # Levantar contenedor
      - name: Run container
        run: |
          docker run -d -p ${{ github.event.inputs.PORT }}:${{ github.event.inputs.PORT }} --name devops-api-container devops-api
          sleep 5

      # Instalar Hurl (herramienta para pruebas de API)
      - name: Setup hurl (API testing tool)
        uses: gacts/install-hurl@v1

      # Ejecutar pruebas Hurl
      - name: Test API
        run: |
          hurl --variable host=http://localhost:${{ github.event.inputs.PORT }} \
               --error-format long \
               --test session.hurl
